name: Staticcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  staticcheck:
    name: Run Staticcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Staticcheck
        run: |
          dirs=$(go list ./... | grep -v '/example')
          staticcheck $dirs
